services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./docker-entrypoint.sh
    command: npm start
    volumes:
      - node_modules:/app/node_modules:cached
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          #ignore:
          # By default everything from Dockerignore will not be synced
          # - add other files and folders to not sync with container
        - action: rebuild
          path: package.json
    environment:
      - PORT=3001
      - BROWSER=none
    stdin_open: true
    tty: true

volumes:
  node_modules:
